if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(VTK_DIR "D:/Toolkit/VTK/VTK-9.2.0.rc2-install-debug/lib/cmake/vtk-9.2")
else()
    set(VTK_DIR "D:/Toolkit/VTK/VTK-9.2.0.rc2-install-release/lib/cmake/vtk-9.2")
endif()